const data = [
    { userName: "Alice Smith", appearance: "offline" },
	{ userName: "Eva White", appearance: "busy" },
	{ userName: "John Doe", appearance: "online" },
	{ userName: "Charlie Brown", appearance: "online" },
	{ userName: "Mia Clark", appearance: "busy" },
	{ userName: "Bob Johnson", appearance: "idle" },
	{ userName: "Grace Lee", appearance: "offline" },
	{ userName: "David Taylor", appearance: "idle" },
	{ userName: "Jack Anderson", appearance: "idle" },
	{ userName: "Olivia Wilson", appearance: "offline" },
	{ userName: "Frank Davis", appearance: "online" },
	{ userName: "Sophie Miller", appearance: "online" },
	{ userName: "Olivia King", appearance: "idle" },
	{ userName: "Kim Robinson", appearance: "busy" },
	{ userName: "Liam Harris", appearance: "online" },
	{ userName: "Nathan Hall", appearance: "offline" },
	{ userName: "Peter Moore", appearance: "busy" },
	{ userName: "Quinn Turner", appearance: "online" },
	{ userName: "Rose Parker", appearance: "offline" },
	{ userName: "Leo King", appearance: "busy" },
	{ userName: "Sam Evans", appearance: "idle" },
	{ userName: "Tom Bennett", appearance: "busy" },
	{ userName: "Henry Anderson", appearance: "offline" },
	{ userName: "Emma Davis", appearance: "idle" },
	{ userName: "Daniel Harris", appearance: "busy" },
	{ userName: "Ava White", appearance: "online" },
	{ userName: "Owen Robinson", appearance: "offline" },
	{ userName: "Lucas Taylor", appearance: "offline" },
	{ userName: "Isabella Turner", appearance: "idle" },
	{ userName: "Lily Brown", appearance: "online" },
];

export default data;