const data = [
	{
		id: 1,
		userName: "Alice Smith",
		appearance: "offline",
		pfp: "//unsplash.it/seed/1/500/250",
	},
	{
		id: 2,
		userName: "Eva White",
		appearance: "busy",
		pfp: "//unsplash.it/seed/2/500/250",
	},
	{
		id: 3,
		userName: "John Doe",
		appearance: "online",
		pfp: "//unsplash.it/seed/3/500/250",
	},
	{
		id: 4,
		userName: "Charlie Brown",
		appearance: "online",
		pfp: "//unsplash.it/seed/4/500/250",
	},
	{
		id: 5,
		userName: "Mia Clark",
		appearance: "busy",
		pfp: "//unsplash.it/seed/5/500/250",
	},
	{
		id: 6,
		userName: "Bob Johnson",
		appearance: "idle",
		pfp: "//unsplash.it/seed/6/500/250",
	},
	{
		id: 7,
		userName: "Grace Lee",
		appearance: "offline",
		pfp: "//unsplash.it/seed/7/500/250",
	},
	{
		id: 8,
		userName: "David Taylor",
		appearance: "idle",
		pfp: "//unsplash.it/seed/8/500/250",
	},
	{
		id: 9,
		userName: "Jack Anderson",
		appearance: "idle",
		pfp: "//unsplash.it/seed/9/500/250",
	},
	{
		id: 10,
		userName: "Olivia Wilson",
		appearance: "offline",
		pfp: "//unsplash.it/seed/10/500/250",
	},
	{
		id: 11,
		userName: "Frank Davis",
		appearance: "online",
		pfp: "//unsplash.it/seed/11/500/250",
	},
	{
		id: 12,
		userName: "Sophie Miller",
		appearance: "online",
		pfp: "//unsplash.it/seed/12/500/250",
	},
	{
		id: 13,
		userName: "Olivia King",
		appearance: "idle",
		pfp: "//unsplash.it/seed/13/500/250",
	},
	{
		id: 14,
		userName: "Kim Robinson",
		appearance: "busy",
		pfp: "//unsplash.it/seed/14/500/250",
	},
	{
		id: 15,
		userName: "Liam Harris",
		appearance: "online",
		pfp: "//unsplash.it/seed/15/500/250",
	},
	{
		id: 16,
		userName: "Nathan Hall",
		appearance: "offline",
		pfp: "//unsplash.it/seed/16/500/250",
	},
	{
		id: 17,
		userName: "Peter Moore",
		appearance: "busy",
		pfp: "//unsplash.it/seed/17/500/250",
	},
	{
		id: 18,
		userName: "Quinn Turner",
		appearance: "online",
		pfp: "//unsplash.it/seed/18/500/250",
	},
	{
		id: 19,
		userName: "Rose Parker",
		appearance: "offline",
		pfp: "//unsplash.it/seed/19/500/250",
	},
	{
		id: 20,
		userName: "Leo King",
		appearance: "busy",
		pfp: "//unsplash.it/seed/20/500/250",
	},
	{
		id: 21,
		userName: "Sam Evans",
		appearance: "idle",
		pfp: "//unsplash.it/seed/21/500/250",
	},
	{
		id: 22,
		userName: "Tom Bennett",
		appearance: "busy",
		pfp: "//unsplash.it/seed/22/500/250",
	},
	{
		id: 23,
		userName: "Henry Anderson",
		appearance: "offline",
		pfp: "//unsplash.it/seed/23/500/250",
	},
	{
		id: 24,
		userName: "Emma Davis",
		appearance: "idle",
		pfp: "//unsplash.it/seed/24/500/250",
	},
	{
		id: 25,
		userName: "Daniel Harris",
		appearance: "busy",
		pfp: "//unsplash.it/seed/25/500/250",
	},
	{
		id: 26,
		userName: "Ava White",
		appearance: "online",
		pfp: "//unsplash.it/seed/26/500/250",
	},
	{
		id: 27,
		userName: "Owen Robinson",
		appearance: "offline",
		pfp: "//unsplash.it/seed/27/500/250",
	},
	{
		id: 28,
		userName: "Lucas Taylor",
		appearance: "offline",
		pfp: "//unsplash.it/seed/28/500/250",
	},
	{
		id: 29,
		userName: "Isabella Turner",
		appearance: "idle",
		pfp: "//unsplash.it/seed/29/500/250",
	},
	{
		id: 30,
		userName: "Lily Brown",
		appearance: "online",
		pfp: "//unsplash.it/seed/30/500/250",
	},
];

export default data;